name: Deploy website to EC2 using AWS CodeDeploy 
 
on: 
  push: 
    branches: 
      - aws-deploy 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v3 
 
    - name: Login to Docker Hub 
      uses: docker/login-action@v3 
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
 
    - name: Build and push Docker image 
      run: | 
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/api . 
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api:latest 
    
 
    - name: Deploy to AWS CodeDeploy 
      run: | 
        aws deploy create-deployment \ 
          --application-name todo__app \ 
          --deployment-group-name todo--api-deployment-group \ 
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}       
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        AWS_REGION: us-east-2 
          
